# Generated by Django 3.0.4 on 2020-03-16 17:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='E:\\MyApp\\src\\media')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=300)),
                ('speciality', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('post', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trans_id', models.IntegerField()),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Art')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=datetime.datetime(2020, 3, 16, 23, 25, 11, 43709))),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Art')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300)),
                ('artid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Art')),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='art_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Artist'),
        ),
    ]
