# Generated by Django 3.0.4 on 2020-03-17 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200316_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='instock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 15, 56, 38, 733217)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 15, 56, 38, 734213)),
        ),
    ]
