# Generated by Django 3.0.4 on 2020-03-20 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200320_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 20, 58, 40, 700023)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 20, 58, 40, 700023)),
        ),
    ]
